<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200304152035 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mycompany_mypackage_domain_model_dancer ADD country VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE mycompany_mypackage_domain_model_dancer ADD CONSTRAINT FK_1542125D5373C966 FOREIGN KEY (country) REFERENCES mycompany_mypackage_domain_model_country (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_1542125D5373C966 ON mycompany_mypackage_domain_model_dancer (country)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE mycompany_mypackage_domain_model_dancer DROP FOREIGN KEY FK_1542125D5373C966');
        $this->addSql('DROP INDEX IDX_1542125D5373C966 ON mycompany_mypackage_domain_model_dancer');
        $this->addSql('ALTER TABLE mycompany_mypackage_domain_model_dancer DROP country');
    }
}